### ISSUE TITLE
Enabling "scroll the track label" option causes unnecessary clipping

### ISSUE THREAD

**Issue by queenbiscuit311** [sakithb/media-controls#100]
For some reason, if the scrolling track label option is enabled, the name of the track that is playing will be clipped 100% of the time regardless of how long it is. It also caused clipping in other top bar buttons like the "places status indicator" extension button when I was using that. These unnecessarily clipped short titles don't scroll either, they're just stuck like that.

![image](https://github.com/sakithb/media-controls/assets/88851292/028ca4a8-b991-4cb0-83dd-7a35c34ca5e2)

![image](https://github.com/sakithb/media-controls/assets/88851292/62cf49a3-b27b-411b-8adb-c7c563fc158b)

**Comment by ChrisLauinger77** [comment]
Maximum widget with 1 ?
What happens when you default it to 200 or disable it with settings it to 0 ?

**Comment by queenbiscuit311** [comment]
it's not actually one, my theme does that in tweaks windows for some reason it's making s 3 digit text box 1 digit long. I have mine set to like 200 now, but I'll check again. the size I chose didn't really matter cause this still appears to happen

**Comment by ChrisLauinger77** [comment]
I have the feeling your theme is not really adjusted to newer gnome shell versions. Can U please try the default one. It should be fine there.

**Comment by queenbiscuit311** [comment]
It does the same thing if I turn off my shell theme, unfortunately.

**Comment by queenbiscuit311** [comment]
Let me try something

**Comment by queenbiscuit311** [comment]
![image](https://github.com/sakithb/media-controls/assets/88851292/e6047a4b-62ae-4f89-8e4e-3b2d3c9462c6)
disabled all theming I had, still no change unfortunately.

**Comment by queenbiscuit311** [comment]
Also, it would appear the button glitch is just on this extension's settings page and maybe some others, seems to think it should be a single digit number. The theme works everything else so it's probably just a bug I need to submit to the theme repo

**Comment by ChrisLauinger77** [comment]
What is this symbol in your last screenshot on the very left top (next to the activities/workspace switcher control) ?
Could another enabled extension cause this ?
What happens when you turn off other extensions and only media-controls is enabled ?

**Comment by queenbiscuit311** [comment]
that symbol is arc menu. I already tried disabling my shell theme, removing the environment variable that sets my GTK theme, and disabling all extensions except this one with no effect, extension seems to behave exactly the same no matter what I do.

**Comment by queenbiscuit311** [comment]
not quite sure what it could be if it doesn't happen for you. I could try the extension in a clean environment like a VM to make sure it's not something more deeply hidden in my environment.

**Comment by ChrisLauinger77** [comment]
I use a VM - and it is only clipping when it needs to.

**Comment by queenbiscuit311** [comment]
any song with a name short enough to not need clipping with my current settings appears to do this

**Comment by ChrisLauinger77** [comment]
strange - I cannot confirm this happens to me

**Comment by queenbiscuit311** [comment]
I'll try it on a VM myself and see if there's something deep in my configuration that's causing it and tell you the results. not sure what the cause would be but it is possible it's just my system

**Comment by queenbiscuit311** [comment]
![image](https://github.com/sakithb/media-controls/assets/88851292/c1a7efbf-369d-41da-845b-4ca04804da68)

I've confirmed the issue doesn't exist in a vm, but i dont have the slightest idea what about my setup specifically is causing it.

**Comment by ChrisLauinger77** [comment]
Am Freitag, dem 27.10.2023 um 03:42 -0700 schrieb queenbiscuit311:
> image
> I've confirmed the issue doesn't exist in a vm, but i dont have the
> slightest idea what about my setup specifically is causing it.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

Me neither but it seems its not a problem of the extension ...
