### ISSUE TITLE
System Freeze when playing media with mpv

### ISSUE THREAD

**Issue by HJavid010** [sakithb/media-controls#101]
Hi
Today I noticed system freeze for a couple of seconds (between 10 to 40) when playing a media with mpv for first time.

I don't know how to gather required information and traces so I would be grateful if you help me with this.

**Comment by ChrisLauinger77** [comment]
Am Freitag, dem 27.10.2023 um 03:56 -0700 schrieb HJavid:
> Hi
> Today I noticed system freeze for a couple of seconds (between 10 to
> 40) when playing a media with mpv for first time.
> I don't know how to gather required information and traces so I would
> be grateful if you help me with this.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

Why you think this is a problem of the extension ?
I never observed freezes tbh.
Is this 100% reproducible with the mpv file ?

**Comment by ChrisLauinger77** [comment]
Please also add more info: https://github.com/sakithb/media-controls#reporting-issues

**Comment by HJavid010** [comment]
Hi again

i'm on fedora 38, gnome 44.5

bug is easily reproducible and occurs even when i disable all other extensions

when i play a video file with mpv(a video player) the system completely freezes, i cant even go to tty in that moment
after 20 seconds system restores and system doesn't hang till next login.

**Comment by ChrisLauinger77** [comment]
When I play a video file with mpv video player the extension is not even shown.
Seems mpv has no MPRIS interface. Any plugins for mpv used ?

**Comment by ChrisLauinger77** [comment]
Found the mpv-mpris package. I can play videos with this player. I also got some freeze 1 time when I dragged a file inside the player but I could not reproduce it a second time.
Probably the mpris implementation of mpv to blame. It seemds to be the reason for the freeze as all other players I use do not have this problem.
