### ISSUE TITLE
Why media-controls pop-up doesn't show song and artist name?

### ISSUE THREAD

**Issue by makecraft** [sakithb/media-controls#109]
![Captura desde 2023-11-14 17-44-45](https://github.com/sakithb/media-controls/assets/117121011/80fe7447-268d-4586-a008-93710ece5b60)

Gnome 45 | Wayland

**Comment by ChrisLauinger77** [comment]
I would say - the player seems supported.
But the media which is played does not have any information about the song / artist...

**Comment by makecraft** [comment]
@ChrisLauinger77 tested with another song:

![Captura desde 2023-11-16 11-36-12](https://github.com/sakithb/media-controls/assets/117121011/5c997321-e80e-47aa-9760-be48107d82b6)

And the metadata is correct:
![imagen](https://github.com/sakithb/media-controls/assets/117121011/54858bbb-10f0-40ad-b441-f09e5e9112e2)

In media controls in Gnome notifications they are well shown:

![Captura desde 2023-11-16 11-43-19](https://github.com/sakithb/media-controls/assets/117121011/0cbb6984-3cb9-496c-a1f5-afc095d3d08c)

**Comment by ChrisLauinger77** [comment]
What version of gnome / the extension is used ?

**Comment by makecraft** [comment]
@ChrisLauinger77 Gnome 45 / Release v28

**Comment by ChrisLauinger77** [comment]
Not a lollipop user - but installed it to  check.
![Bildschirmfoto vom 2023-11-17 07-44-10](https://github.com/sakithb/media-controls/assets/3518684/bb84f6e5-5d1f-4d14-af51-90a325d50e3f)

debian trixie/sid - also gnome 45 - media-controls from main branch. it works for me.
what does happen when the same media is used but another player like VLC or rythmbox ?

**Comment by makecraft** [comment]
@ChrisLauinger77 the same with VLC:

![imagen](https://github.com/sakithb/media-controls/assets/117121011/69de0950-6a23-4b8d-945f-6fb0814a3171)

Rhythmbox:

![imagen](https://github.com/sakithb/media-controls/assets/117121011/d04e344f-28f1-4963-b6ba-92a86f156a57)

Lollypop version in Manjaro:

![imagen](https://github.com/sakithb/media-controls/assets/117121011/4ad54fb1-896d-4fae-8c3c-605f7e35d214)

**Comment by ChrisLauinger77** [comment]
It looks like a general problem on the machines installation. 
What about playing a video on youtube ? Like in firefox or chrome

**Comment by makecraft** [comment]
@ChrisLauinger77 It was shown in Gnome 44 but when I updated Gnome 45 nope

Firefox neither
![imagen](https://github.com/sakithb/media-controls/assets/117121011/700ebaf1-7c47-4c52-978b-69da063331f2)

**Comment by sakithb** [comment]
While playing some media, run this command in a terminal. `busctl --user list | grep -i MediaPlayer2`. For example usually the bus name for spotify is `org.mpris.MediaPlayer2.spotify`. Then copy the bus name of the player and run this command `busctl --user introspect {bus name here} /org/mpris/MediaPlayer2`. Post the output here, it could be helpful.

**Comment by makecraft** [comment]
@sakithb 
![Captura desde 2023-11-17 18-37-32](https://github.com/sakithb/media-controls/assets/117121011/a4cce241-a12c-4ebd-a211-f9a8c96a5948)
![Captura desde 2023-11-17 18-37-45](https://github.com/sakithb/media-controls/assets/117121011/02c0cc94-eff1-43bd-b9a8-240dbc19f797)

**Comment by sakithb** [comment]
Seems like your media player is fine. How did you install the extension, did you use eog or another method?

**Comment by makecraft** [comment]
@sakithb I installed it from https://extensions.gnome.org/

**Comment by makecraft** [comment]
Media Controls v30, it looks fixed 
![imagen](https://github.com/sakithb/media-controls/assets/117121011/092cf4af-5144-4d88-bb55-3040bfb44027)
