### ISSUE TITLE
Gnome crashes

### ISSUE THREAD

**Issue by tovarish88** [sakithb/media-controls#110]
hi, 

sometimes gnome crashes (looks like after screen locking and unlocking) with the following message in journal:

ноя 17 14:33:38 sstepanov gnome-shell[315438]: Object .Gjs_mediacontrols_cliffniff_github_com_widget_MediaControls (0x559786a36460), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(),

**Comment by ChrisLauinger77** [comment]
#102 fixed in main branchj not released yet in EGO

**Comment by tovarish88** [comment]
cool. thx

**Comment by sakithb** [comment]
Reopening because, even though the crashes are fixed, the graphical bug is yet to be fixed.

**Comment by sakithb** [comment]
Fixed in bea3c92
