### ISSUE TITLE
Fedora 39 + Gnome 45.1 - Doesn't work

### ISSUE THREAD

**Issue by BuzzKnightbeer** [sakithb/media-controls#112]
I upgraded to Fedora 39 with Gnome 45.1 a while ago, and the extension manager says the "current Gnome version is not supported" (mouseover on red clock in the screenshot). What's the best way of getting it to work again? I would prefer a method that doesn't involve loading the extension through a different system...

![Pasted image](https://github.com/sakithb/media-controls/assets/45749699/33094a9e-2b8e-46af-8f00-fba286c11e04)

**Comment by sakithb** [comment]
Try removing the extension. Logging out and logging in and installing it again.

**Comment by ChrisLauinger77** [comment]
https://extensions.gnome.org/extension/4470/media-controls/
There should be also the option to update

**Comment by BuzzKnightbeer** [comment]
> Try removing the extension. Logging out and logging in and installing it again.

That worked. Thank you!

> https://extensions.gnome.org/extension/4470/media-controls/ There should be also the option to update

It just gives me an installation button and when clicking it the Extension Manager opens, but it did not resolve the issue.
