### ISSUE TITLE
Crash to Log-in screen 

### ISSUE THREAD

**Issue by SimonBlancoE** [sakithb/media-controls#113]
The system crashes to login screen when pressing the Super key. Doesn't happen 100% of the time.

Here are the relevant logs:

Nov 20 08:27:05 localhost.localdomain gnome-shell[20464]: JS ERROR: TypeError: this._extension.settings is undefined
                                                          updateWidgetWidths@file:///home/octo/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:541:30
                                                          initWidgets@file:///home/octo/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:246:18
                                                          updatePlayer@file:///home/octo/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/widget.js:493:33
                                                          unhidePlayer@file:///home/octo/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/widget.js:555:26
                                                          _playerPropsChanged@file:///home/octo/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:353:41
                                                          @resource:///org/gnome/shell/ui/init.js:21:20
Nov 20 08:27:05 localhost.localdomain gnome-shell[20464]: Window manager warning: Trying to remove non-existent keybinding "mediacontrols-toggle-trackinfomenu".
Nov 20 08:27:05 localhost.localdomain gnome-shell[20464]: Window manager warning: Trying to remove non-existent keybinding "mediacontrols-toggle-trackinfomenu".
Nov 20 08:26:30 localhost.localdomain gnome-shell[20464]: Window manager warning: Trying to remove non-existent keybinding "mediacontrols-toggle-trackinfomenu".
Nov 20 08:26:30 localhost.localdomain gnome-shell[20464]: Window manager warning: Trying to remove non-existent keybinding "mediacontrols-toggle-trackinfomenu".

Some info about the System:
System:
  Kernel: 6.6.1-1-default arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
    Desktop: GNOME v: 45.1 tk: GTK v: 3.24.38 wm: gnome-shell dm: GDM v: 45.0.1
    Distro: openSUSE Tumbleweed 20231117

**Comment by sakithb** [comment]
This has been fixed in v30, which is in review.
