### ISSUE TITLE
Not working on Fedora Workstation 39.

### ISSUE THREAD

**Issue by pragit-raj-sharma** [sakithb/media-controls#117]
Extension version - 31
Gnome - 45.2
Fedora Workstation 39

Error - this.player.containerControls is undefined

![image](https://github.com/sakithb/media-controls/assets/65211497/603c9864-a6dd-4090-8503-068ff62d6383)

**Comment by ChrisLauinger77** [comment]
Can you try to remove it and install it again fromm E.G.O. ?
I have it running on debian testing and it works for every player I tested.
FF Chromium VLC spotify spotube ...

**Comment by ChrisLauinger77** [comment]
And of course after an extension update the gnome-shell needs to be restarted to load all the changes.

**Comment by pragit-raj-sharma** [comment]
I tried to reinstall but it didn't resolve the issue.

**Comment by ChrisLauinger77** [comment]
No idea why its not working 4 u. If it would be a general problem we would have more reports. Seems something on the local machine isn't right.
Can U attach a log file ? Or even the zipped extension folder ?

**Comment by pragit-raj-sharma** [comment]
> No idea why its not working 4 u. If it would be a general problem we would have more reports. Seems something on the local machine isn't right. Can U attach a log file ? Or even the zipped extension folder ?

yeah sure, but don't know where to look for the log.

**Comment by ChrisLauinger77** [comment]
> > No idea why its not working 4 u. If it would be a general problem we would have more reports. Seems something on the local machine isn't right. Can U attach a log file ? Or even the zipped extension folder ?
> 
> yeah sure, but don't know where to look for the log.

not sure at Fedora either.  so zip the extensions folder and attach it - I wanna compare whats installed to what should be

**Comment by pragit-raj-sharma** [comment]
[extensions.zip](https://github.com/sakithb/media-controls/files/13696528/extensions.zip)

there it is..
 I recently noticed it does work sometimes for a few minutes when logging in but then then just disappears with the above-mentioned error message in the extensions manager.

**Comment by ChrisLauinger77** [comment]
You have the newest version of all files. Thats not the problem - but I have no idea what it,
Some package of gnome / javascript might be nor updated on the local machine. I am not a fedora user.
Maybe somebody else knows what can be checked on fedora. For me at debian it works.

**Comment by gmg137** [comment]
openSUSE Tumbleweed's gnome 45.2 has the same problem.

**Comment by pragit-raj-sharma** [comment]
> openSUSE Tumbleweed's gnome 45.2 has the same problem.

do you know any fix for it..?

**Comment by gmg137** [comment]
> do you know any fix for it..?

I don't know, I had that problem after a recent update.

**Comment by Gen3ric** [comment]
This is the error I get:
```console
Dec 23 10:15:41 fedora gnome-shell[2357]: JS ERROR: Extension <mediacontrols@cliffniff.github.com>: Error: Extension point conflict: there is already a status indicator for role media_controls_extension
                                          addToStatusArea@resource:///org/gnome/shell/ui/panel.js:937:19
                                          enable@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/widget.js:270:24
                                          enable@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/extension.js:10:21
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:252:38
                                          async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:606:24
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:705:18
                                          createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                          enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:276:29
                                          _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:301:40
                                          async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:134:41
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Dec 23 10:15:41 fedora gnome-shell[2357]: Ignoring length property that isn't a number at line 1, col 12
Dec 23 10:15:41 fedora gnome-shell[2357]: JS ERROR: TypeError: app is null
                                          get icon@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:1082:21
                                          initWidgets@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:124:17
                                          updatePlayer@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/widget.js:505:33
                                          _connectDbus/<@file:///home/username/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/widget.js:407:26
                                          async*asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
                                          @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by shmu26** [comment]
I can confirm that it is not working on Fedora Workstation 39.
