### ISSUE TITLE
Settings crashing and incorrect positioning

### ISSUE THREAD

**Issue by qexat** [sakithb/media-controls#128]
The media controls used to be on the left of my top bar and few days ago they started sitting at the center.

I opened the extension settings from the gnome extension app but the pop-up disappears after one second and cannot be opened again afterwards.
I tried disabling every extension but this one, but this does not fix the issue.

I have no idea on how to get debug logs or something like that, apologies.

## Config

OS: EndeavourOS 2022.08.28 64-bit (Linux 6.7.0-arch3-1)
Gnome: 45.3

**Comment by sakithb** [comment]
Thanks for reporting the issue, what is the extension version, you can see this in the extensions app.

**Comment by sakithb** [comment]
Do you mean the extension popup disappears?

**Comment by qexat** [comment]
> Do you mean the extension popup disappears? If yes, your issue is related to https://gitlab.gnome.org/GNOME/gjs/-/issues/598 . You can temporarily fix this by downgrading the gjs package to 1.78.1
> 
> Downgrade the package in Arch-based systems: `sudo pacman -U https://archive.archlinux.org/packages/gjs/gjs-2:1.78.1-1-x86_64.pkg.tar.zst`

This fixes my issue, thank you very much for your quick response!
