### ISSUE TITLE
Please Add an option to display album image instead of player icon or along with it.

### ISSUE THREAD

**Issue by zuwf** [sakithb/media-controls#130]

**Comment by ChrisLauinger77** [comment]
I guess he is talking about the panel - I do not think it is useful - panel is very small in height. The album will not look good.

**Comment by zuwf** [comment]
Sorry for the unclear request 😬. I asked the same you understood. colourful icons changing for respective songs in panel is some how visually appetising for the peoples like me with colourful panels
