### ISSUE TITLE
Invalid next track icon

### ISSUE THREAD

**Issue by atashi764** [sakithb/media-controls#132]
![image](https://github.com/sakithb/media-controls/assets/40156662/a84ec8d3-1629-4656-b6f4-d09ad77953db)

pretty self explanatory huh?

**Comment by sakithb** [comment]
Does it go away after re-enabling the extension?

**Comment by ChrisLauinger77** [comment]
> ![image](https://private-user-images.githubusercontent.com/40156662/301495117-a84ec8d3-1629-4656-b6f4-d09ad77953db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDI2NzQsIm5iZiI6MTcwNjgwMjM3NCwicGF0aCI6Ii80MDE1NjY2Mi8zMDE0OTUxMTctYTg0ZWM4ZDMtMTYyOS00NjU2LWI2ZjQtZDA5YWQ3Nzk1M2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1NDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMDM5NDk1OGUyYzhlYmNmZjY5NDU1NDU0MGY5Njk4NTkxMDNiN2FhMWRiOTA5OTIxMzQ0YmYyYzg0MTJmMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OtQ7hgnVZvqEwF7vQdqBLmiEBl0NI1mCIQn9tC2Gr9M)
> 
> pretty self explanatory huh?

A picture says more than 1000 words

**Comment by ChrisLauinger77** [comment]
![grafik](https://github.com/sakithb/media-controls/assets/3518684/feb23e51-d04f-4380-b1bc-ddbda3935763)
i just tested this and it works. arent those icons part of the theme ?
Can you try another icon theme ? What theme is used ?

**Comment by kaibutsu764** [comment]
I used this 

![image](https://github.com/sakithb/media-controls/assets/40156662/7a01eaa1-18eb-49a8-9498-fcbe164d7e2c)

and btw switching icons fixed it even for the one i was using. not sure if it will persist

**Comment by kaibutsu764** [comment]
**### update: it's only happening with with the yaru themes**

**Comment by sakithb** [comment]
Does the correct icon show in other places, like in the notification list while playing a song?

**Comment by atashi764** [comment]
![image](https://github.com/sakithb/media-controls/assets/40156662/d4fe29c7-85d7-493e-a5fc-325882dea7b8)
you mean this?

yes it does

**Comment by atashi764** [comment]
![image](https://github.com/sakithb/media-controls/assets/40156662/04067949-48bf-4afc-b1f7-9d0a5092f240)
with yaru

**Comment by ChrisLauinger77** [comment]
So the yaru theme has the wrong icon. maybe report it to them

**Comment by atashi764** [comment]
have no idea but it's disturbing as i often click next instead of seek

**Comment by ChrisLauinger77** [comment]
Use another theme OR report the bug to be fixed in the yaru theme

**Comment by atashi764** [comment]
i see. can i fix it myself?

**Comment by ChrisLauinger77** [comment]
I guess. Mirror the prev track icon and store it under the next track icon name.
U need to know how the icons are named.
Maybe ask teh yaru guys. https://github.com/ubuntu/yaru

**Comment by sakithb** [comment]
@atashi764 just to be sure, can you post the output of this command: `dconf dump /org/gnome/shell/extensions/mediacontrols/`

**Comment by atashi764** [comment]
@sakithb 

$ dconf dump /org/gnome/shell/extensions/mediacontrols/
```
[/]
colored-player-icon=false
element-order=['icon', 'title', 'controls', 'menu']
extension-index=0
extension-position='center'
hide-media-notification=false
max-widget-width=150
mouse-actions=['toggle_play', 'toggle_info', 'none', 'none', 'none', 'none', 'none', 'none']
prefer-using-seek=false
seperator-chars=['|', '|']
show-player-icon=true
show-playpause-icon=true
show-seek-forward=true
show-seperators=false
show-sources-menu=false
track-label=['track', '', 'none']

```

**Comment by atashi764** [comment]
![image](https://github.com/sakithb/media-controls/assets/40156662/cdf2f2d5-6f75-491a-813b-8f640c03d136)
this might help

**Comment by sakithb** [comment]
Can you try playing around with enabling/disabling the next and seek forward icons in preferences.

**Comment by atashi764** [comment]
![image](https://github.com/sakithb/media-controls/assets/40156662/d177f56e-5cd9-4259-a195-404c6d166a7c)

tried.
![image](https://github.com/sakithb/media-controls/assets/40156662/3bb3cad2-a317-46ff-9a4d-529d8cb01a8a)

**Comment by ChrisLauinger77** [comment]
This settings screenshots are not from the latest version. They are from the version we do not maintain any more. What GNOME version is used ?

**Comment by atashi764** [comment]
this is gnome 42. ubuntu 22.04.3

**Comment by ChrisLauinger77** [comment]
We do only maintain gnome 45 or later. 
U can update to a newer ubuntu LTS in April it seems. 

https://www.omgubuntu.co.uk/2023/10/ubuntu-24-04-release-date-set-for-april-25-2024

**Comment by mervick** [comment]
This issue is not related to themes but looks like a bug with css in older versions of gnome-shell.

For those still using older versions of GNOME Shell (version 42 in my case), follow these steps to fix this issue:

Navigate to the installed extension:
```bash
cd ~/.llocal/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com
```

 In the `player.js` file, find the lines where the icons are initialized. Update the code by adding the `media-icon` class to the `style_class` for each icon, like this:

```js
// Player controls

this.iconSeekBack = new St.Icon({
    icon_name: "media-seek-backward-symbolic",
    style_class: "system-status-icon media-icon"
});
this.iconPrev = new St.Icon({
    icon_name: "media-skip-backward-symbolic",
    style_class: "system-status-icon media-icon",
});
this.iconPlayPause = new St.Icon({
    icon_name: this.isPlaying
        ? "media-playback-pause-symbolic"
        : "media-playback-start-symbolic",
    style_class: "system-status-icon media-icon",
});
this.iconNext = new St.Icon({
    icon_name: "media-skip-forward-symbolic",
    style_class: "system-status-icon media-icon",
});
this.iconSeekForward = new St.Icon({
    icon_name: "media-skip-backward-symbolic",
    style_class: "system-status-icon media-icon"
});
```

At the bottom of `stylesheet.css`, add the following:

```css
.panel-button .system-status-icon.media-icon {
    width: 12px;
    height: 12px;
    margin: 0 2px;
    padding: 0 4px;
}
```

With these changes, you should see the icons working properly.
After editing, remember to reload GNOME Shell for the changes to take effect.

![Image](https://github.com/user-attachments/assets/72cb09c4-76e5-49e0-be0d-28287bc048a1)
