### ISSUE TITLE
Marquee title/artist display supportive

### ISSUE THREAD

**Issue by clover-yan** [sakithb/media-controls#133]
When the panel space is tight, marquee display will be helpful to save area.

`spotify-tray` supports that, it is a good example.

**Comment by ChrisLauinger77** [comment]
No ifea what is meant here ...

**Comment by clover-yan** [comment]
@ChrisLauinger77 When panel is nearly full, we can't see the whole track name. Marquee is a solution.

Here's an example of the marquee way of [`spotify-tray`](https://github.com/esenliyim/sp-tray).

[Screen record](https://github.com/sakithb/media-controls/assets/56215525/38ec1014-ea2c-4b62-a0c1-d0e034e4434c)

I'd appreciate if you could consider adding this feature.

**Comment by ChrisLauinger77** [comment]
You can enable scrolling. You know that, right ?

**Comment by sakithb** [comment]
> @ChrisLauinger77 Right, it is an enhancement. When panel is nearly full, we can't see the whole track name. Marquee is a solution.
> 
> Here's an example of the marquee way of [`spotify-tray`](https://github.com/esenliyim/sp-tray).
> 2024.02.03.15.53.01.webm
> 
> I'd appreciate if you could consider adding this feature.
> 
> **Edit**: I've seen 'Scroll labels' in the screenshot in Readme. It may be the same feature, but I use GNOME 42 so I didn't see it in my extension. If so, please ignore my dumb issue.

We've decided not to push new updates for GNOME shell versions below 42. I've added a similar feature in the latest version of the extension which is only for GNOME 45.

**Comment by clover-yan** [comment]
No matter what, thank you all. 

I'd wait for Ubuntu 24.04 LTS and enjoy the feature then.

**Comment by ChrisLauinger77** [comment]
That's why it is important to add gnome version / extension version to an issue.
@sakithb cant we make a BUG template on github ?

**Comment by ChrisLauinger77** [comment]
Yes we can:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
