### ISSUE TITLE
Add Tidal-hifi support

### ISSUE THREAD

**Issue by avicarpio** [sakithb/media-controls#137]
**Is your feature request related to a problem? Please describe.**
Tidal-hifi app is not supported and the media control does not appear.

**Describe the solution you'd like**
I would like that media controls have support for the Tidal-hifi app: https://github.com/Mastermindzh/tidal-hifi

**Comment by ChrisLauinger77** [comment]
The extension supports all apps which have the MPRIS interface.
Did you switch on the MPRIS interface ?
![grafik](https://github.com/sakithb/media-controls/assets/3518684/cbcab222-e837-4ec3-8436-a35520435486)
