### ISSUE TITLE
Not compatible with GNOME 46

### ISSUE THREAD

**Issue by MahtoSujeet** [sakithb/media-controls#141]
The GNOME Shell Extensions website and GNOME Extensions app say that it's out of date.

**Environment:**
 - Distro: Arch Linux 6.8.1-arch1-1
 - GNOME version 46

**Comment by ChrisLauinger77** [comment]
https://github.com/sakithb/media-controls/pull/136
Everthing is done - only the update on EGo is missing...

**Comment by sakithb** [comment]
Published to EOG. I will release on here later today.

**Comment by mmmmmob** [comment]
Hi, I just got a notification of the update on my Extension Manager (I'm using Gnome 46 on Arch).

After update there's still no media player show up on my panel as on my Gnome 45 -- not sure if there's a bug somewhere or not?

I tried turn off other extensions I'm using but Media Controls and it still doesn't show up.

*My previous setting is it'd be show at the center beside the clock*
![image](https://github.com/sakithb/media-controls/assets/141404845/2eafba95-7bbb-4adb-9d83-ba31586e91ea)

**Comment by MahtoSujeet** [comment]
> Hi, I just got a notification of the update on my Extension Manager (I'm using Gnome 46 on Arch).
> 
> After update there's still no media player show up on my panel as on my Gnome 45 -- not sure if there's a bug somewhere or not?
> 
> I tried turn off other extensions I'm using but Media Controls and it still doesn't show up.

I'm experiencing the same. I removed extensions, installed again, then rebooted. Notification doesn't show up when playing media.

Extension version: 2.0.1
OS: Arch 6.8.1

**Comment by remisiki** [comment]
I just upgraded to `gnome-shell 46` and got this error on ver `2.0.1`

```
[Media Controls] Error: Failed to call listener for property IsInvalid: TypeError: options.menuProps is undefined
                                              removeButtonControlIcon@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PanelButton.js:647:22
                                              addButtonControls@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PanelButton.js:574:22
                                              updateWidgets@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PanelButton.js:114:26
                                              PanelButton@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PanelButton.js:48:14
                                              addPanelButton@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/extension.js:460:25
                                              setActivePlayer@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/extension.js:417:22
                                              addPlayer/<@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/extension.js:355:22
                                              callOnChangedListeners@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PlayerProxy.js:118:25
                                              validatePlayer@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PlayerProxy.js:98:14
                                              callOnChangedListeners@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PlayerProxy.js:118:25
                                              initPlayer/<@file:///home/remisiki/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/helpers/shell/PlayerProxy.js:37:22
                                              _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                              _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
                                              @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by sakithb** [comment]
I will revert the update till this is fixed.

**Comment by ChrisLauinger77** [comment]
@sakithb I have it runnig on GNOME46 - I see 2 commits in main:
https://github.com/sakithb/media-controls/commit/c72bc4e52662d56c85d94b743ef489b60dacca93
https://github.com/sakithb/media-controls/commit/64d786357fe1fbbb96ab5b20d9413a1613eca4d6
Is there more to fix ?
Or what is hindering the release ?

**Comment by sakithb** [comment]
> @sakithb I have it runnig on GNOME46 - I see 2 commits in main: [c72bc4e](https://github.com/sakithb/media-controls/commit/c72bc4e52662d56c85d94b743ef489b60dacca93) [64d7863](https://github.com/sakithb/media-controls/commit/64d786357fe1fbbb96ab5b20d9413a1613eca4d6) Both are about TS conversion to JS... Is there more to fix ? Or what is hindering the release ?

A bunch of issues were reported above by people using the GNOME 46 version, I am waiting for the release of fedora 40 to test and debug the issues on my own.

**Comment by sakithb** [comment]
The extension's under review, should be accepted soon!
Please open seperate issues for issues in the new version.
