### ISSUE TITLE
Show Tab Favicon instead of Browser Icon

### ISSUE THREAD

**Issue by Arbee4ever** [sakithb/media-controls#142]
**Is your feature request related to a problem? Please describe.**
When I play a Video within my Browser I don't easily see what Website it is from

**Describe the solution you'd like**
It would be nice if there was an Option to show the tabs favicon instead of the Browser Icon

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sakithb** [comment]
This is out of the scope of this project, the extension will show whatever the icon of the media player is.
