### ISSUE TITLE
Error on new install (?)

### ISSUE THREAD

**Issue by madebylydia** [sakithb/media-controls#144]
**Describe the bug**
I meant to update the extension. Upon update, the extension had an error.
Re-installing did not help.

**To Reproduce**
1. Simply installing the extension, or updating

**Expected behavior**
To be installed.

**Screenshots**
It just fails with "ERROR" in red.
![image](https://github.com/sakithb/media-controls/assets/61093863/6a41af20-1952-4c44-a659-21320fe84ab2)

**Environment:**
 - Distro: Fedora 39
 - GNOME version: 45.5
 - Extension Version: 2.0.1
 
 I might be an absolute dummy, but I have no idea where I can get a traceback. So, if you know how to get one for you, LMK!

**Comment by ChrisLauinger77** [comment]
After the update login and logout does usually help. Thats a gnome-shell update thing not the problem of the extenion.

**Comment by madebylydia** [comment]
😅 Yes, that fixed it... Thank you for your help.
I don't know if I should blame me for not trying such an easy step, or blame GNOME for having such a weird issue.

**Comment by ChrisLauinger77** [comment]
> 😅 Yes, that fixed it... Thank you for your help. I don't know if I should blame me for not trying such an easy step, or blame GNOME for having such a weird issue.

Well gnome updates the extension itself - usually it tells login / out to update the pending extensions.
When you do it by hand on EGO - the login / out is just mandatory
