### ISSUE TITLE
Add ability to split into two items

### ISSUE THREAD

**Issue by Jak2k** [sakithb/media-controls#145]
**Is your feature request related to a problem? Please describe.**
I would like to place the song name left and the buttons right of the clock, so that the clock is centered.

**Describe the solution you'd like**
Add option to split song info and controls into different panel items.

**Describe alternatives you've considered**

**Additional context**

**Comment by sakithb** [comment]
Thanks for your suggestion but adding this feature will introduce all kinds of complications, and will mean redoing/rethinking the structure of the extension.
