### ISSUE TITLE
Keyboard shortcuts for all actions

### ISSUE THREAD

**Issue by fernandovmacedo** [sakithb/media-controls#147]
It would be nice to be able to set keyboard shortcuts to all the extension actions, not only showing the popup menu.

As for alternatives, I'm not very knowledgeable about how gnome works, but maybe describe some way to set up the shortcuts directly in dconf extension properties or another cli only way.

**Comment by ChrisLauinger77** [comment]
I disagree - the app you want to control should have shortcuts not the extension ...

**Comment by sakithb** [comment]
I agree with Chris, unless the shortcut you are requesting is a shortcut for a standard mpris method/action, it is not the extension's job to add it.
