### ISSUE TITLE
Hide popup menu

### ISSUE THREAD

**Issue by Amereyeu** [sakithb/media-controls#150]
**Is your feature request related to a problem? Please describe.**
When notification area is open in gnome 46 and I accidentaly move mouse over the media controls popup menu shows up instead   
 
**Describe the solution you'd like**
I would like an option in settings to hide popup menu from showing altogether or on mouseover   

**Additional context**
Right now I have popup menu set up to show on mouse click which is fine but still have to position media controls to other part of panel than I would like..

**Comment by sakithb** [comment]
This is the default behavior for popups on GNOME. Try with any other popup, it will behave the same.

**Comment by Amereyeu** [comment]
I know that. So its not possible to show popup only on mouse click? (fe. ArcMenu will show menu only when I click on its icon)

**Comment by sakithb** [comment]
It is possible, but I don't see why it is necessary.

**Comment by Amereyeu** [comment]
alright. thanks
