### ISSUE TITLE
Ubuntu 24.04 LTS Gnome 46 not working

### ISSUE THREAD

**Issue by marci-n-owak** [sakithb/media-controls#152]
**Description:**
Extension just doesn't work. Nothing is shown in the panel, as well as feature Hide the media notification. 

I tried also to install it from the source, but no difference

![Screenshot from 2024-05-16 10-00-12](https://github.com/sakithb/media-controls/assets/51361528/a8cc4450-bed9-464a-8ecb-8ffe2386e524)

![Screenshot from 2024-05-16 10-01-35](https://github.com/sakithb/media-controls/assets/51361528/f080a98c-44d0-4492-8b16-f7eea792995a)

**Environment:**
 - Distro: Ubuntu 24.04 LTS
 - GNOME version 46
 - Extension Version: 2.0.1

**Comment by ChrisLauinger77** [comment]
Please see #137
