### ISSUE TITLE
Progress bar on media does not show properly

### ISSUE THREAD

**Issue by kimjongbing** [sakithb/media-controls#156]
**Describe the bug**
On any media (music, video, etc) the progress of the video is not reflected on the bar. It will not show media length, it will just be 00:00 to 00:00.

**To Reproduce**
1. Open any video and play it
2. Click to see the media controls and progress bar
3. Progress bar will be greyed out and not reflecting any media progress.

**Expected behavior**
The duration of the video being shown and the progress of how far the user is in the video.

**Screenshots**
![image](https://github.com/sakithb/media-controls/assets/126769537/86d123bf-db0d-4f38-9ab6-13b84c6a593a)

**Environment:**
 - Distro: Arch Linux
 - GNOME version 46.2
 - Extension Version 36

**Comment by ChrisLauinger77** [comment]
Have you tried a different browser ? It might the MPRIS implementation of the player and not the extension ...

**Comment by kimjongbing** [comment]
> Have you tried a different browser ? It might the MPRIS implementation of the player and not the extension ... Maybe try with chromium / chrome ?

Hi Chris. It does seem to work fine in a Chromium based browser. Is there a way to fix it so that it can work in Firefox?

**Comment by ChrisLauinger77** [comment]
Maybe ask the firefox people to fix their MPRIS implementation ...

**Comment by kimjongbing** [comment]
> Maybe ask the firefox people to fix their MPRIS implementation ...

Ok thanks I asked them here https://bugzilla.mozilla.org/show_bug.cgi?id=1903560
