### ISSUE TITLE
It Scales some images on overview very big. like filling the whole screen

### ISSUE THREAD

**Issue by kibugenzaKing** [sakithb/media-controls#158]
**Describe the bug**
It scales some songs image very big, like too big to even fit the screen 

**To Reproduce**
1. Download this song (it's not specific to that song, it happens to many songs): https://1drv.ms/u/s!Ar8ig3kKZVEeojK81QxHrNhvSxnz?e=8OAprw  
2. Open that song in Vlc media

**Expected behavior**
3. It will be very huge, covering all screen. 

**Screenshots**
![Screenshot from 2024-07-08 00-20-41](https://github.com/sakithb/media-controls/assets/139082006/b5c357f9-6bd6-4650-8552-766db321299e)
![Screenshot from 2024-07-08 00-28-41](https://github.com/sakithb/media-controls/assets/139082006/84bdc8f1-5bb7-4a68-8fa4-8485b0140ec4)

![Screenshot from 2024-07-08 00-29-31](https://github.com/sakithb/media-controls/assets/139082006/614deec2-e45f-47c7-9ebb-7db4f7040c10)
![Screenshot from 2024-07-08 00-30-23](https://github.com/sakithb/media-controls/assets/139082006/07bcfa9a-5e4c-41b1-aebe-db564d052a09)
![Screenshot from 2024-07-08 00-34-07](https://github.com/sakithb/media-controls/assets/139082006/a4f347da-4115-4f4d-b8a8-602624a62ab2)

**Environment:**
 - Distro: [debian 12 Bookworm (wayland)]
 - GNOME version [43]
 - Extension Version [29]
 - Computer: Macbook Air 2015, 1400*900 display

**Additional context**
Hope this issue, gets solved.

the last two songs scale fine, i think the bug is related to somehow if the song doesn't have metadata like Title and artist name it scales large???  because the last two songs have full metadata and they scale fine

and the screenshots are of my whole laptop screen, not cropped

**Comment by ChrisLauinger77** [comment]
When it looks strange - the media name is weird as well. It seems the mp3 tags in the media are not correctly OR contain weird characters. Maybe try to fix the mp3 tags.
https://packages.debian.org/bookworm/easytag you can correct the mp3 info with this tool.
The version you are using it not maintained any more - only gnome 45 and newer - but anyways I think its the media and not the extension
