### ISSUE TITLE
Udemy Player Problem

### ISSUE THREAD

**Issue by aliramazanov** [sakithb/media-controls#160]
### **Issue Description:**
When using the extension to control the playing or pausing of a video on the Udemy platform, it doesn't work correctly. Instead of triggering the play/pause button, it triggers the forward or rewind button.

### **Steps to Reproduce:**
Go to Udemy.
Click on any course and start playing the video.
Try to control the video using the extension and observe that it doesn't work properly.

### **Environment:**
Distro: Fedora 40
GNOME Version: 46
Extension Version: 2.0.1

**Comment by ChrisLauinger77** [comment]
It sounds to me that the udemy players MPRIS implementation is borked.

**Comment by sakithb** [comment]
I agree with Chris. @aliramazanov is it the same on all browsers?

**Comment by aliramazanov** [comment]
Sorry guys, false alaram! I tested on multiple browsers and it doesn't work. Thanks for the extenstion by the way!

**Comment by aliramazanov** [comment]
Sorry guys, false alaram! I tested on multiple browsers and it doesn't work. Thanks for the extenstion by the way!
