### ISSUE TITLE
This extension is causing serious memory leak

### ISSUE THREAD

**Issue by kev1nweng** [sakithb/media-controls#166]
**Describe the bug**
With this extension enabled, everytime the track information changes (e.g. Next Track), `gnome-shell` consumes more memory and won't free up the previously used garbage memory. 

**To Reproduce**
1. With the extension enabled, open up a random music player or browser
2. Play a music or video
3. Seek for next track or click on new videos
4. Repeat step 3
5. After some time the issue can clearly be identified

**Expected behavior**
Memory consumption of `gnome-shell` should remain ~300MB. 

**Screenshots**
![image](https://github.com/user-attachments/assets/29fb97d2-928d-4abe-81e5-86ed306830e8)
`gnome-shell` memory consumption after about 50 tracks change

**Environment:**
 - Distro: Debian testing
 - GNOME version 46.4
 - Extension Version 2.0.1

**Additional context**
THIS IS A SERIOUS PROBLEM POTENTIALLY PREVENTING THE WHOLE OS FROM WORKING PROPERLY. 
**_IT SHOULD BE ADDRESSED AS SOON AS POSSIBLE._**

**Comment by ChrisLauinger77** [comment]
Same as #138 - and it does not on every setup
