### ISSUE TITLE
Media player icon incorrect for Firefox

### ISSUE THREAD

**Issue by BlagoGunev** [sakithb/media-controls#167]
Firefox is not displayed as an icon in the player, rather the default music player icon is displayed

![image](https://github.com/user-attachments/assets/840395c8-5f39-4a9e-a2b0-99c95743995c)

Using Fedora 40 with latest versions of packages, GNOME 46.4 Wayland

**Comment by ChrisLauinger77** [comment]
Probably because of the used icon theme. It works with the default one, right ?

**Comment by ChrisLauinger77** [comment]
![grafik](https://github.com/user-attachments/assets/a07c02b4-2a28-4f7f-9433-018c0db1dd05)
works with my icon theme

**Comment by BlagoGunev** [comment]
It is not due to the icon theme, happens with the default Adwaita
![image](https://github.com/user-attachments/assets/e19c96f1-7428-42d6-b62d-ac4190bb1250)
It has also worked in the past with the same icon theme.

**Comment by ChrisLauinger77** [comment]
Then I would say a package is not installed. gnome-icon-theme
Or something else wrong on the local disk. Defenetly not a problem of the extension
