### ISSUE TITLE
Album art - low resolution

### ISSUE THREAD

**Issue by fero-sk** [sakithb/media-controls#169]
**Describe the bug**
When the widget width is set to 630, the album art is displayed with very low resolution.

**To Reproduce**
1. Set widget width to e.g. 630.
2. Open the popup widget.

**Expected behavior**
Display high quality image.

**Screenshots**
![Snímka obrazovky zo dňa 2024-09-26 20-28-50](https://github.com/user-attachments/assets/25e9fa8f-ddd4-4390-b547-439b12807c4a)

**Environment:**
 - Distro: Ubuntu 24.04
 - GNOME version 46
 - Extension Version 2.0.2

**Comment by ChrisLauinger77** [comment]
What media do you play ?
Is this an mp3 where the album art is included ?
How can the extension show low res album art in high res ?

**Comment by fero-sk** [comment]
Chrome (Youtube music) - HQ album art is there included.

**Comment by ChrisLauinger77** [comment]
> Chrome (Youtube music) - HQ album art is there included.

I only have spotify. No youtube music account to check. Spotify works like a charm

**Comment by fero-sk** [comment]
Firefox - everything works fine. Chrome - both youtube music & spotify - low resolution.

**Comment by ChrisLauinger77** [comment]
> Firefox - everything works fine. Chrome - both youtube music & spotify - low resolution.

So file a bug at chrome.
