### ISSUE TITLE
For the browser, the volume doesn't change

### ISSUE THREAD

**Issue by alkunit** [sakithb/media-controls#171]
**Describe the bug**
When running video or audio in a browser, such as Firefox, you can't adjust the volume with the mouse wheel.

**To Reproduce**
1. Open the Firefox browser
2. Go to the page with any media content
3. Play media
4. Move the cursor over the player control
5. Move the mouse wheel up and down

**Expected behavior**
Changes the volume of the video or audio that is running in the browser

**Screenshots**
-

**Environment:**
 - Distro: [e.g. Ubuntu 24.10]
 - GNOME version [47]
 - Extension Version [2.0.2]

**Additional context**
Checked for Firefox and Floorp browsers

**Comment by ChrisLauinger77** [comment]
floorp is firefox based - so seems a firefox problem

**Comment by ChrisLauinger77** [comment]
#156 in this issue a link to the FF issue
