### ISSUE TITLE
App audio device switcher

### ISSUE THREAD

**Issue by DanHolli** [sakithb/media-controls#178]
**Is your feature request related to a problem? Please describe.**
I have an Astro Mix Amp USB DAC which has an "game" and "chat" output. I'd like to move some apps/stream manually to the opposite channel so I can utilize the built in mixer on the fly while in games

**Describe the solution you'd like**
Add an (optional) output switcher per-app/steam so I can switch output

**Describe alternatives you've considered**
Manually switching via PulseAudio Volume Control: it works perfectly fine, but it would be nice to not need to open it

**Additional context**
PAVC while splitting audio in playback menu (yes, it's using a dummy stream, but I promise it works)
![image](https://github.com/user-attachments/assets/a0aabb13-47c9-4676-b640-f7802b15e5a9)

PAVC Output Devices
![image](https://github.com/user-attachments/assets/23cfcff8-4982-47ce-acea-c2b8c6643435)

current extension
![image](https://github.com/user-attachments/assets/c35760d1-ffa6-4bca-9594-97ce5f3dbeda)

Gnome Settings
![image](https://github.com/user-attachments/assets/2d861a2f-aeb4-42c4-954b-c5d707790164)

**Additional Notes**
I'd be happy to test any changes or provide more information

**Comment by ChrisLauinger77** [comment]
It is not the intention of the extension to control the audio output devices.
We only control the player over the MPRIS interface.

It can be done in gnome like this:
![grafik](https://github.com/user-attachments/assets/6bf6b39a-bab8-4f53-b284-8c9f835e33a7)

OR there are other extensions for that purpose on EGO
https://extensions.gnome.org/extension/751/audio-output-switcher/
https://extensions.gnome.org/extension/1028/gnome-shell-audio-output-switcher/

**Comment by DanHolli** [comment]
I feel like there's been a bit of a misunderstanding
those extensions change the default output device which is not what I'm looking for and is included in modern Gnome 

I'm asking to add a new feature that doesn't appear to exist in another extension

Let me restate what I'm looking for
You've got app volume sliders (see image 3 from OG post)
I want a dropdown on the side of the app slider to change the output channel/device for that specific app as shown in image 1 of original post (take note of the seperate outputs for Floorp and the dummy speach dispatcher)

**Comment by ChrisLauinger77** [comment]
Still I think it is not the job of this extension.
We control the volume of the player over the MPRIS interface (implemented by the player).
Our extension has no volume slider. (no idea where the "current extension" screenshot is from thb)
Which version of media-controls do you use ?

**Comment by DanHolli** [comment]
🤦man I feel stupid. sorry for bothering you, I clicked for the wrong extension
I love this extension and you are correct, it does exactly what I want it to do
again, sorry for wasting your time

the correct one I was looking for was Quick Settings Audio Panel 🤦
I'll make a request there

**Comment by ChrisLauinger77** [comment]
No worries
