### ISSUE TITLE
Icon not loading

### ISSUE THREAD

**Issue by domi413** [sakithb/media-controls#179]
**Describe the bug**  
When playing music on Spotify, the default music note icon is displayed instead of the Spotify icon. However, if I disable and then re-enable the extension, the correct Spotify icon appears.

**To Reproduce**  
1. Enable the plugin
2. Open Spotify and play a song
3. Observe the icon in the top bar (it will show the music note icon)
4. Disable and re-enable the plugin (the correct Spotify icon will then be displayed)

**Screenshots**
![image](https://github.com/user-attachments/assets/74d7250c-c5af-4f5c-9164-e299ce747f50)

**Environment:**
 - Distro: EndeavourOS
 - GNOME version 47.2
 - Extension Version 2.0.2

**Comment by ChrisLauinger77** [comment]
Maybe same as #167 - could be theme related. Does it work with the adwaita theme ?

**Comment by domi413** [comment]
no, same issue

**Comment by ChrisLauinger77** [comment]
> no, same issue

I do not understand "no, same issue".
Try another gnome theme - maybe the default one. It works on my side - no reason it should not work on yours other then something on the local machine.

**Comment by domi413** [comment]
I used the default theme, but the issue persists. I'll test this on a fresh VM when I have time, to check if there might be a configuration causing the problem.

**Comment by ChrisLauinger77** [comment]
In #167 there is also a package mentioned at the end.

**Comment by domi413** [comment]
I tested it on a fresh Fedora VM and a fresh Endeavour VM (with all GNOME dependencies installed...), but the issue persists. I think the problem lies with this plugin. I may take a look at the source code, but that will take a a couple weeks since I'm currently studying for my exams.

**Comment by ChrisLauinger77** [comment]
Maybe its the way spotify is installed ? native package or flatpak ?

**Comment by domi413** [comment]
On Fedora, I used Flatpak, while on Arch, I used the AUR package, which I think packages the official Spotify version.

**Comment by ChrisLauinger77** [comment]
![Bildschirmfoto vom 2024-12-30 08-53-44](https://github.com/user-attachments/assets/9529d4f1-39e6-48c4-91c0-a6b36d734231)
I tested it also in a fedora 41 VM - i get this ...

**Comment by domi413** [comment]
So another attempt from my side...

**Steps to reproduce the issue:**

1. Installed **Fedora 41** in a VM.
2. Installed **Spotify** from Flathub.
3. Installed **Extension Manager** from Flathub.
4. Opened Spotify and logged in.
5. Installed **media-controls** extension from Extension Manager.
6. Opened Spotify and played a song.  
   → The Spotify icon appears in the top bar.
7. Disabled the plugin and closed spotify according to the following steps from my initial issue:
 > 1. Enable the plugin
    2. Open Spotify and play a song
    3. Observe the icon in the top bar (it will show the music note icon)
    4. Disable and re-enable the plugin (the correct Spotify icon will then be displayed)
    
   → **Issue**: The Spotify icon didn't appear.

8. Disabled and enabled the extension again (with spotify open)
   → **The Spotify icon shows up**, but this behavior was already expected.  
   → I just want to make it clear that the order of enabling/disabling the plugin is relevant here.

9. After closing and reopening Spotify:  
   → **The Spotify icon does not show up.**

---


- **Sometimes, the Spotify icon appears after the initial plugin toggle, but this behavior is inconsistent. If you open and close Spotify multiple times, this issue will  occur, where the icon fails to appear.**



It seems like there’s something odd going on since it works on your side but not on mine. It may help if someone else could try to reproduce this bug to confirm whether it’s a consistent issue.

**Comment by ChrisLauinger77** [comment]
What do you mean by enable / disable the plugin ?
If you mean by plugin the extension - why you disable it anyways. I never do that. I do not see any reason for disabling the extension. 
And If you for some reason disable it. Then enable it BEFORE you start spotify.

**Comment by domi413** [comment]
> What do you mean by enable / disable the plugin ?

You can toggle the plugin on/off with the Extensions app.

> I do not see any reason for disabling the extension.

Me neither, but this is the way to reproduce the issue...

> Then enable it BEFORE you start spotify.

This is the way the issue occurs ;)


@sakithb, would you mind trying to reproduce it? :)

**Comment by ChrisLauinger77** [comment]
> > What do you mean by enable / disable the plugin ?
> 
> You can toggle the plugin on/off with the Extensions app.
> 
It is an extension not a plugin.
> > I do not see any reason for disabling the extension.
> 
> Me neither, but this is the way to reproduce the issue...
> 
So do not disable it - then there is no issue...

> > Then enable it BEFORE you start spotify.
> 
> This is the way the issue occurs ;)
> 
I have it enabled all the time - no issues.
> @sakithb, would you mind trying to reproduce it? :)
Is there a point in wasting time on this ?

**Comment by domi413** [comment]
nevermind, i'm wasting my time here
