### ISSUE TITLE
Now Playing field

### ISSUE THREAD

**Issue by ardentperf** [sakithb/media-controls#182]
**Is your feature request related to a problem? Please describe.**
When I stream online radio stations with VLC, I'm able to see the radio station name in the "title" field.  VLC itself doesn't show an artist field, but it shows another field called "Now Playing" which shows the title of the current song that's playing on the stream. I don't know whether this field is available in the metadata that's available to the media-controls extension, wondering if someone else here knows?

**Describe the solution you'd like**
If the "Now Playing" field is available, then would be nice to have that as an option for the display string.

**Comment by ChrisLauinger77** [comment]
Can you post an example link to a online radio station you listen to ?

**Comment by ardentperf** [comment]
sure, here are a few that were in the VLC media library and exhibit this behavior:
* http://ekila1.pro-fhi.net:2600/stream
* http://relay.publicdomainradio.org:80/classical.mp3
* http://c3.radioboss.fm:8185/live

screenshot of VLC (ncurses mode):
![image](https://github.com/user-attachments/assets/2013154e-fde2-4bcc-968d-cde27a732d66)

**Comment by ChrisLauinger77** [comment]
![grafik](https://github.com/user-attachments/assets/f78799ff-9cb7-43a4-9bfb-3773c80b9d1e)
it seems VLC specific and can only work in some cases - I doubt it makes sense to add it ..

**Comment by ardentperf** [comment]
Nice - I didn't know you could do that with D-Spy.

I just tried one of those streams with RhythmBox and discovered that RhythmBox puts the song title in the title metadata. So this does seem to be some kind of quirk of VLC

Thanks for taking a look, and for the pointer to D-Spy

![image](https://github.com/user-attachments/assets/d40359e0-97af-4cb5-9e35-89cd71eba2ff)
