### ISSUE TITLE
Please add seeking media 

### ISSUE THREAD

**Issue by BruceWayne-Linux** [sakithb/media-controls#33]
Please add the ability to seek the current track, much like Kde-plasma
Example:- (https://user-images.githubusercontent.com/87817029/139195855-e271532a-a871-4c1c-94ce-a311d9961f8c.png)

**Comment by THEBATEZIOPARKER** [comment]
Is the ability to seek media added in new update ?

**Comment by cliffniff** [comment]
I didn't have enough time and needed to add GNOME 41 support, so it will probably be the next update.

**Comment by THEBATEZIOPARKER** [comment]
ok

**Comment by sakithb** [comment]
WIP in seek-ft

**Comment by ChrisLauinger77** [comment]
work in progress for main branch gnome 45
![Bildschirmfoto vom 2023-10-17 23-54-30](https://github.com/sakithb/media-controls/assets/3518684/fa3c11fd-6494-4e83-b3fd-a2733cecd8b2)
this _ornament stuff does not work any more - need to find out how it can be done better ... @sakithb

**Comment by ChrisLauinger77** [comment]
![Bildschirmfoto vom 2023-10-18 00-21-31](https://github.com/sakithb/media-controls/assets/3518684/b3072c3c-b3e2-4abe-a79e-e07b7c565ae5)
have it working

**Comment by sakithb** [comment]
The ornament dots should be probably removed, I will do that in the meantime

**Comment by ChrisLauinger77** [comment]
Without my last change it would look like this:
![grafik](https://github.com/sakithb/media-controls/assets/3518684/3123f351-610f-465b-997f-900c3ca794f0)
I added the ornament.DOT and it looked better

**Comment by sakithb** [comment]
The ornaments are kind of unnecessary in this context, let's keep this issue open until we figure out a workaround.

**Comment by ChrisLauinger77** [comment]
I think my misstake was
                this._infoItem.setOrnament(PopupMenu.Ornament.DOT);
line 583 player.js should be removed

**Comment by ChrisLauinger77** [comment]
without the ornament.DOT on slider - the slider looks like in my prev screenshot
![Bildschirmfoto vom 2023-10-18 16-38-57](https://github.com/sakithb/media-controls/assets/3518684/3b17132a-59cc-43c3-89b5-8b43f4026cf6)
this is how it looks like in current commit in main @sakithb
