### ISSUE TITLE
title doesnt disappear after closing the media source in chromium based browsers

### ISSUE THREAD

**Issue by arejula27** [sakithb/media-controls#35]
Bug: After seeing a vidio on yt and clisng it, the title continues beeing on the extension. 
A better behaviour should be detecting the source is eneded and doesnt show it.

**Comment by cliffniff** [comment]
This issue was noticed before and was fixed. To get a more understanding on this issue, I need your browser and browser version. Also tell me whether you closed the browser or just the tab.

**Comment by Deottive** [comment]
I am having the same bug sometime when I close the spotify web app from Edge the panel notification of media does dissappear but most of the time does not 

I am using Spotify web app from Microsoft edge 
![image](https://user-images.githubusercontent.com/71910027/151476024-21240d9d-43bf-4a47-ada2-d62b9e98e710.png)
Please dont roast me for using Edge.

**Comment by Wendy-Russo** [comment]
Same Issue, using brave [v 1.44.112] and ubuntu 22.04

**Comment by ChrisLauinger77** [comment]
It seems like the guy who uses Edge closes the tab.
I never observed this with Firefox though. Seems more like a browser related issue then a general one ...
Edge (on linux) , brave are some exotic configurations.

**Comment by ChrisLauinger77** [comment]
I tested it with chrome - played a YT video. Closed the tab. The player controls did not disappear.
I needed to close the browser to get rid of them.

**Comment by ChrisLauinger77** [comment]
chrome / brave / edge are all chromium https://www.chromium.org/chromium-projects/ based browsers which have this issue.

**Comment by ChrisLauinger77** [comment]
Maybe some browser extension helps ?
https://github.com/beingmohit/browser-playerctl

**Comment by sakithb** [comment]
Probably need to look if there is a fix we can do on our side.

**Comment by ChrisLauinger77** [comment]
Found something intresting in another MPRIS extension issue list:
https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/28
So defenetly broken on chromium based browsers. 
But he also applied a workaround checking for some MPRIS capabilities ...
