### ISSUE TITLE
Option to align the pop-up to left or right, or add minimum width

### ISSUE THREAD

**Issue by KristianOde** [sakithb/media-controls#37]
When you use the pop-up menu to play the next song, the pop-up menu will adjust it's position if the displayed text on the panel isn't the same as the previous song. This makes sense as the pop-up is centered based on width of the panel entry, but I feel like it's awkward to use if you keep skipping songs using the pop-up menu. Maybe you could add an option to align the pop-up to one of the sides of the panel item to make it's position always be the same. Alternatively, add a minimum widget width alongside the max option to have the panel item always the same size (this would probably be a better solution). I hope my request makes sense.

**Comment by cliffniff** [comment]
Alright, I will add this in the next update.

**Comment by ChrisLauinger77** [comment]
I think I would rename the "max widget with" to "widget with" and add an option if it should be threated as max (the current behaviour) or as fixed (what the issue asks for).

**Comment by ChrisLauinger77** [comment]
An idea: how about let the track info menu size just be the same size as track label menu ?

**Comment by sakithb** [comment]
> An idea: how about let the track info menu size just be the same size as track label menu ?

I have no idea, I tried to do this in the past but failed if I remember correctly, are you working on this issue? If not I can start working on this.

**Comment by ChrisLauinger77** [comment]
Really I failed ? Would it not be the same code where you set the size of track label menu ?
I am not working on that - I just had this idea and it would also not require an additional setting.
Max widget size (for both widgets)

**Comment by ChrisLauinger77** [comment]
https://github.com/sakithb/media-controls/pull/120
