### ISSUE TITLE
Remove warnings in the GJS console

### ISSUE THREAD

**Issue by G-dH** [sakithb/media-controls#39]
https://github.com/cliffniff/media-controls/issues/28#issuecomment-940590085
https://github.com/cliffniff/media-controls/blob/a6187136e104eafd46aedf002e4a455df040cc1c/prefs.js#L183
gjs in 3.36 doesn't know `??` operator, it's too new.

**Comment by cliffniff** [comment]
I fixed this in the latest release. Are you sure you are on the latest version?

**Comment by G-dH** [comment]
See for yourself, I linked your own code in the main branch, didn't find anything newer.
Btw the extension itself fills my log with `Ignoring length property that isn't a number at line ...` and `clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed`.
But otherwise it works, thanks for your work!

**Comment by cliffniff** [comment]
Oh I am sorry, I remember fixing that, but somehow I haven't pushed it I guess. I will add the changes.

**Comment by cliffniff** [comment]
Haha, no they are just warnings, nothing harmful. They are printed out when a song or a button updates. I guess I will have to cleanup them I guess.

**Comment by G-dH** [comment]
I was just curious, I would fix it myself, because I hate unnecessary warnings. I'm also developing extensions and therefore I'm watching the log constantly :)

**Comment by cliffniff** [comment]
Oh nice. I will fix up the warnings when I have some time. If you could fix it, of course it would be appreciated. Also I will change the title to removing warnings.

**Comment by ChrisLauinger77** [comment]
I could get rid of the 
`clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed.`
messages.
But I have no idea where the
`Ignoring length property that isn't a number at line ...`
messages are coming from @sakithb
Any hint what I have to check ?

**Comment by G-dH** [comment]
@ChrisLauinger77 Check `stylesheet.css` ;)

    Ignoring length property that isn't a number at line 22, col 18
    Ignoring length property that isn't a number at line 21, col 17

**Comment by ChrisLauinger77** [comment]
> @ChrisLauinger77 Check `stylesheet.css` ;)
> 
> ```
> Ignoring length property that isn't a number at line 22, col 18
> Ignoring length property that isn't a number at line 21, col 17
> ```

Ah that lines are about stylesheet.css - barely use it in my other extensions.
Thx for pointing that out.

**Comment by ChrisLauinger77** [comment]
main and gnome44
