### ISSUE TITLE
Add album name support (plus, one more toggle in the track label)

### ISSUE THREAD

**Issue by paveloom** [sakithb/media-controls#40]
Hello there. I would like to request a feature that allows to put album name in the track label. Currently, I can't check the name of an album in UI at all, only its cover art. I would like to have something like `Earmake — Parallels — Between Good and Evil` in the panel.

Alternatively, having album name in the track information menu would be nice.

**Comment by cliffniff** [comment]
Alright I will add it.

**Comment by richo67** [comment]
That would be great top have album name visble.
