### ISSUE TITLE
Does not consume scroll events when used with scroll panel

### ISSUE THREAD

**Issue by bodgars** [sakithb/media-controls#41]
Hi,
When used with an extension such as [Scroll Panel](https://extensions.gnome.org/extension/4257/scroll-panel/) this extension will not consume the scroll event, leading to the panel also switching. See mrEDitor/gnome-shell-extension-scroll-panel#15 for a better explanation than I can muster as well as an example fix.

**Comment by cliffniff** [comment]
Hi thanks for your feedback, I will apply the fix as soon as possible.
