### ISSUE TITLE
Add volume controls to track information menu

### ISSUE THREAD

**Issue by PatrickJosh** [sakithb/media-controls#50]
Hey,
first of all, thank you for this great extension! I have a small improvement idea: Would it be possible to add a volume control in terms of a slider to the track information menu? Many applications have separate volume controls and especially if you use GSConnect to control your media on your phone if would be very handy to be able to control the volume level.

**Comment by sakithb** [comment]
There is no way to practically implement this. Where would the slider go in the popup, without making it look weird?

**Comment by ChrisLauinger77** [comment]
But Volume up / down can be bound to Mouse actions - I think a good compromise

**Comment by Diegovsky** [comment]
@sakithb can it be just down of the tack position?
