### ISSUE TITLE
[Feature Request] Volume up/down for scroll up/down mouse actions

### ISSUE THREAD

**Issue by HubKing** [sakithb/media-controls#71]
If it is technically possible, please add volume up/down to the drop-down list in Mouse actions. It would be convenient if the user can adjust the song's volume by the scroll wheel, without opening the player's UI.

I mean, not the system audio volume, but the song's volume within the player. For example, Strawberry music player has the volume slider on the bottom-left corner.

![image](https://user-images.githubusercontent.com/10900489/218251809-9bf5ec58-3b41-48e2-a71f-bbca52d9fb55.png)

![image](https://user-images.githubusercontent.com/10900489/218251947-5e810d51-c96e-4181-a695-de259847c096.png)

**Comment by inxendere** [comment]
bump

**Comment by ChrisLauinger77** [comment]
#50 is also about volume control.

**Comment by sakithb** [comment]
I just tested this and it is possible to implement, I will add this to the backlog.

**Comment by ChrisLauinger77** [comment]
does not work with firefox though - maybe update the known issues section ?

**Comment by sakithb** [comment]
> does not work with firefox though - maybe update the known issues section ? VLC worked for me

Firefox probably does not support the mpris methods

**Comment by sakithb** [comment]
Can confirm it doesn't work on chromium based browsers as well

**Comment by ChrisLauinger77** [comment]
So known limitation

**Comment by sakithb** [comment]
Yes
