### ISSUE TITLE
Can't control with touchscreen

### ISSUE THREAD

**Issue by mikemassaro** [sakithb/media-controls#88]
I am unable to use controls (ex: pause/play, track forward/backward) with laptop touch screen.  Grey pill appears when pressed on screen, but control does not execute.

**Comment by ChrisLauinger77** [comment]
Can you control any other extension with the touchscreen I wonder ?

**Comment by mikemassaro** [comment]
Yes I can such as the Espresso (caffiene) coffee cup as well as 
BackSlide wallpaper switcher.

**Comment by ChrisLauinger77** [comment]
I am afraid I cant help here. I do not have a touchscreen. Anything I would change I cant test :(

**Comment by cliffniff** [comment]
I do not have a touchscreen as well :( But I will see if there is any workaround to emulate and test it.

**Comment by sakithb** [comment]
@mikemassaro Does the issue exists on extension preferences as well or just on the controls on the bar?
