### ISSUE TITLE
Hide the default media notification does not work

### ISSUE THREAD

**Issue by sakithb** [sakithb/media-controls#97]
![Image](https://github.com/sakithb/media-controls/assets/53598550/09ce046a-eef3-43b2-809c-b02bd26dd9a9)

Does not work on gnome 44.

**Comment by sakithb** [comment]
4c93b3c

**Comment by ChrisLauinger77** [comment]
@sakithb It looks like in gnome45 there is no media notification any more. I try the changed code anyways and it results into exceptions in log - so I do not overtake it to main.
Should we hide the row in settings for now ?

**Comment by sakithb** [comment]
I'll see what I can do, and if the setting should be removed, then I will overtake it to main
