### ISSUE TITLE
Media controls not working for Chrome

### ISSUE THREAD

**Issue by ghostxne** [sakithb/media-controls#99]
I've opened a few tabs with media playing (YouTube, Spotify) in Chrome, but I can't pause or skip it using the taskbar controls. 

![Screenshot of media panel](https://github.com/sakithb/media-controls/assets/103334115/d14c9856-b14a-4f61-9d0c-142b68c62e75)

**Comment by ChrisLauinger77** [comment]
Maybe some info about extension version, gnome version etc ?

**Comment by ChrisLauinger77** [comment]
I tested it yesterday with chromium and it worked. Disable all other loaded extensions and try again I would propose.
Maybe some sideeffect with some other extension ?

**Comment by ChrisLauinger77** [comment]
Could it be the tab is already closed. See known limitation for chrome browser
